import type { Metadata } from "next";
import "./globals.css";
import { RegisterProvider } from "@/context/RegisterContext";
export const metadata: Metadata = {
  title: "LRT  X JakOne Pay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-screen" lang="en">
      <body className={`flex h-full w-full flex-col antialiased`}>
        <RegisterProvider>
          <div className="mt-10 flex grow flex-col rounded-t-lg bg-white">
            {children}
          </div>
        </RegisterProvider>
      </body>
    </html>
  );
}
