import type { Metadata } from "next";
import "./globals.css";
import { RegisterProvider } from "@/context/RegisterContext";
export const metadata: Metadata = {
  title: "LRT  X JakOne Pay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-screen " lang="en">
      <body className={`antialiased flex flex-col h-full w-full`}>
        <RegisterProvider>
          <div className="bg-white mt-10 grow rounded-t-lg flex flex-col">
            {children}
          </div>
        </RegisterProvider>
      </body>
    </html>
  );
}
